# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20150709_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(default='http://davebsoft.com'),
            preserve_default=False,
        ),
    ]
