# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
