# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160705_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aptitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
