# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160705_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='scheduled_status',
            field=models.IntegerField(choices=[(1, 'Proposed'), (2, 'Accepting'), (3, 'Scheduled')]),
        ),
    ]
