# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0021_auto_20160711_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
