# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_section_private_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='num_days',
            field=models.IntegerField(default=1),
        ),
    ]
