# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20160716_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
