# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_section_hours_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='duration_per_day',
        ),
    ]
