# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_section_duration_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
