# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20160716_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='hours_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
