# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20160716_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
