/*
 * QuickQuiz
 * Copyright (C) 2005 David C. Briccetti
 * www.davebsoft.com
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 2 of the License, or 
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software Foundation, 
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

package com.dbschools.quickquiz.client.taker;
import java.util.List;
import java.util.ResourceBundle;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

import com.dbschools.quickquiz.Quiz;

/**
 * Prompts for information needed to join a quiz.
 * 
 * @author David C. Briccetti
 */
public final class JoiningDialog extends javax.swing.JDialog {
    private static final long serialVersionUID = -597423074324844616L;

    private final ResourceBundle resources = ResourceBundle.getBundle("quickquiz");
    
    private List<Quiz> quizzes;
    private Quiz selectedQuiz;
    private boolean joinRequested;
    
    /** Creates new form JoiningDialog */
    JoiningDialog(final java.awt.Frame parent, final boolean modal) {
        super(parent, modal);
        initComponents();
        lstQuizNames.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        getRootPane().setDefaultButton(btnJoin);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private final void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        lstQuizNames = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnJoin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle(java.util.ResourceBundle.getBundle("quickquiz").getString("joinQuizTitle"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public final void windowClosing(final java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jScrollPane1.setViewportView(lstQuizNames);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel1.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("quickquiz").getString("playerName").charAt(0));
        jLabel1.setLabelFor(txtPlayerName);
        jLabel1.setText(java.util.ResourceBundle.getBundle("quickquiz").getString("playerName"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        txtPlayerName.setColumns(30);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        getContentPane().add(txtPlayerName, gridBagConstraints);

        btnJoin.setMnemonic(java.util.ResourceBundle.getBundle("quickquiz").getString("joinButton").charAt(0));
        btnJoin.setText(java.util.ResourceBundle.getBundle("quickquiz").getString("joinButton"));
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public final void actionPerformed(final java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });

        jPanel1.add(btnJoin);

        btnCancel.setMnemonic(java.util.ResourceBundle.getBundle("quickquiz").getString("cancelButton").charAt(0));
        btnCancel.setText(java.util.ResourceBundle.getBundle("quickquiz").getString("cancelButton"));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public final void actionPerformed(final java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jPanel1.add(btnCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jPanel1, gridBagConstraints);

        jLabel2.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("quickquiz").getString("quizNameList").charAt(0));
        jLabel2.setLabelFor(lstQuizNames);
        jLabel2.setText(java.util.ResourceBundle.getBundle("quickquiz").getString("quizNameList"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("quickquiz").getString("passwordMnemonic").charAt(0));
        jLabel3.setLabelFor(txtPassword);
        jLabel3.setText(java.util.ResourceBundle.getBundle("quickquiz").getString("quizPasswordIfRequired"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        getContentPane().add(jLabel3, gridBagConstraints);

        txtPassword.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        getContentPane().add(txtPassword, gridBagConstraints);

        final java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }//GEN-END:initComponents

    private final void btnCancelActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setJoinRequested(false);
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private final void btnJoinActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        if (isInputValid()) {
            setJoinRequested(true);
            selectedQuiz = quizzes.get(lstQuizNames.getSelectedIndex());
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, 
                    resources.getString("createDialogInvalidInput"));
        }
    }//GEN-LAST:event_btnJoinActionPerformed
    
    /** Closes the dialog */
    private final void closeDialog(final java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    private boolean isInputValid() {
    	boolean passwordOk = true;
		final String quizPassword = quizzes.get(lstQuizNames.getSelectedIndex()).getPassword();
		final String userPassword = new String(txtPassword.getPassword());
		if (quizPassword != null && ! quizPassword.equals(userPassword)) {
			passwordOk = false;
		}
        return (txtPlayerName.getText().trim().length() > 0) && passwordOk;
    }
    
    void setQuizzes(final List<Quiz> quizzes) {
        this.quizzes = quizzes;
        final DefaultListModel lm = new DefaultListModel();
        for (Quiz quiz : quizzes) {
            lm.addElement(quiz.getName() + " by " + quiz.getGiverName());
        }
        lstQuizNames.setModel(lm);
        lstQuizNames.getSelectionModel().setSelectionInterval(0, 0);
    }
    
    Quiz getSelectedQuiz() {
        return selectedQuiz;
    }
    
    String getPlayerName() {
        return txtPlayerName.getText().trim();
    }
    
    boolean isJoinRequested() {
        return joinRequested;
    }
    
    private void setJoinRequested(final boolean joinRequested) {
        this.joinRequested = joinRequested;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnJoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstQuizNames;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables

}
