package com.dbschools.music.editor;

import com.dbschools.gui.ActionUtil;
import com.dbschools.gui.PopupListener;
import com.dbschools.gui.TableUtil;
import com.dbschools.music.dao.RemoteDao;
import com.dbschools.music.events.Event;
import com.dbschools.music.events.EventObserver;
import com.dbschools.music.orm.AbstractPersistentObject;
import com.dbschools.music.orm.Group;
import java.awt.event.ActionEvent;
import java.lang.Class;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import org.apache.log4j.Logger;
import org.jdesktop.swingx.decorator.HighlighterFactory;

/**
 * Defines groups
 * @author  Dave Briccetti
 */
public class GroupsEditor extends javax.swing.JPanel {
    private static final Logger log = Logger.getLogger(GroupsEditor.class);
    private final RemoteDao remoteDao;
    private final GroupsModel model;

    private static class GroupsModel extends AbstractTableModel {
        private final List<Group> groups = Collections.synchronizedList(new ArrayList<Group>());

        public GroupsModel(RemoteDao remoteDao) {
            super(remoteDao, new String[] {"Group Name", "Test"}, 
                    new Class<?>[] {String.class, Boolean.class}, 
                    new boolean[] {true, true});
            super.setEntities(groups);
            load();
            remoteDao.addEventObserver(new EventObserver() {
                public void notify(Event event) {
                    if (event.getDetails() instanceof Group) {
                        load();
                    }
                }
            });
        }
        
        public Object getValueAt(int rowIndex, int columnIndex) {
            final Group group = groups.get(rowIndex);
            switch(columnIndex) {
                case 0:
                    return group.getName();
                case 1:
                    return group.isDoesTesting();
            }
            return "";
        }
        
        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
            log.info("set value " + aValue + " " + rowIndex + " " + columnIndex);
            final Group group = groups.get(rowIndex);
            switch(columnIndex) {
                case 0:
                    group.setName((String) aValue);
                    break;
                case 1:
                    group.setDoesTesting((Boolean) aValue);
                    break;
            }
            saveOrUpdateObject(group, group.getId());
        }

        protected AbstractPersistentObject getNewEntity() {
            return new Group("untitled", 0, false);
        }

        private void load() {
            groups.clear();
            groups.addAll(remoteDao.getGroups());
            fireTableDataChangedFromSwing();
        }
        
    }
    
    public GroupsEditor(RemoteDao remoteDao) {
        this.remoteDao = remoteDao;
        this.model = new GroupsModel(remoteDao);
        initComponents();
        table.setHighlighters(HighlighterFactory.createSimpleStriping());
        table.setSortable(false);
        table.getColumn(0).setPreferredWidth(250);
        table.getColumn(1).setPreferredWidth(70);
        table.getColumn(1).setMaxWidth(70);
        createActions();
    }

    private void createActions() {
        JPopupMenu popup = new JPopupMenu();
        table.addMouseListener(new PopupListener(table, popup));

        Action deleteAction = new AbstractAction("Delete...") {
            public void actionPerformed(ActionEvent e) {
                int[] selectedRows = table.getSelectedRows();
                if (selectedRows.length > 0) {
                    if (TableUtil.isOkToDelete(GroupsEditor.this, selectedRows.length)) {
                        model.deleteRows(selectedRows);
                    }
                }
            }
        };
        popup.add(new JMenuItem(deleteAction));
        ActionUtil.attachDeleteAction(table, deleteAction);

        Action insertAction = new AbstractAction("Insert") {
            public void actionPerformed(ActionEvent e) {
                model.insertRow();
            }
        };
        popup.add(new JMenuItem(insertAction));
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new org.jdesktop.swingx.JXTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        table.setModel(model);
        jScrollPane1.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("You may only delete groups that contain no members.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable table;
    // End of variables declaration//GEN-END:variables

}
