create sequence "s_assessment_id";
select setval('s_assessment_id', max(id)) from assessment;
create sequence "s_music_user_id";
select setval('s_music_user_id', max(id)) from music_user;
create sequence "s_musician_id";
select setval('s_musician_id', max(id)) from musician;
create sequence "s_music_group_group_id";
select setval('s_music_group_group_id', max(id)) from music_group;
create sequence "s_piece_piece_id";
select setval('s_piece_piece_id', max(id)) from piece;
create sequence "s_instrument_id";
select setval('s_instrument_id', max(id)) from instrument;
create sequence "s_subinstrument_id";
select setval('s_subinstrument_id', max(id)) from subinstrument;
create sequence "s_musician_group_id";
select setval('s_musician_group_id', max(id)) from musician_group;
