/*
 * QuickQuiz
 * Copyright (C) 2005 David C. Briccetti
 * www.davebsoft.com
 *
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 2 of the License, or 
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, write to the Free Software Foundation, 
 * Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

package com.dbschools.quickquiz.client.giver;
import java.util.ResourceBundle;

import javax.swing.JOptionPane;

/**
 * Prompts for information about the quiz being created.
 * 
 * @author David C. Briccetti
 */
public final class QuizCreationDialog extends javax.swing.JDialog implements QuizCreationOptions {
    private static final long serialVersionUID = 7411742717241724285L;

    /** Creates new form QuizCreationDialog */
    QuizCreationDialog(final java.awt.Frame parent, final boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(btnStart);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtGiverName = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("quickquiz"); // NOI18N
        setTitle(bundle.getString("createQuizTitle")); // NOI18N
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("quickquiz").getString("quizName").charAt(0));
        jLabel1.setLabelFor(txtName);
        jLabel1.setText(bundle.getString("quizName")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 3);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("quickquiz").getString("quizPassword").charAt(0));
        jLabel2.setLabelFor(txtPassword);
        jLabel2.setText(bundle.getString("quizPassword")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 0, 3);
        getContentPane().add(jLabel2, gridBagConstraints);

        txtName.setColumns(20);
        txtName.setToolTipText(bundle.getString("tttQuizName")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 3, 8);
        getContentPane().add(txtName, gridBagConstraints);

        btnStart.setMnemonic('S');
        btnStart.setText(bundle.getString("start")); // NOI18N
        btnStart.setToolTipText(bundle.getString("tttStartQuiz")); // NOI18N
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);

        btnCancel.setMnemonic('C');
        btnCancel.setText(bundle.getString("cancelButton")); // NOI18N
        btnCancel.setToolTipText(bundle.getString("tttCancelQuiz")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(jPanel1, gridBagConstraints);

        txtPassword.setColumns(10);
        txtPassword.setToolTipText(bundle.getString("tttQuizPassword")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        getContentPane().add(txtPassword, gridBagConstraints);

        jLabel3.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("quickquiz").getString("quizGiverName").charAt(0));
        jLabel3.setLabelFor(txtGiverName);
        jLabel3.setText(bundle.getString("quizGiverName")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 0, 3);
        getContentPane().add(jLabel3, gridBagConstraints);

        txtGiverName.setColumns(20);
        txtGiverName.setToolTipText(bundle.getString("tttQuizGiver")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 8);
        getContentPane().add(txtGiverName, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private final void btnCancelActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setStartRequested(false);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private final void btnStartActionPerformed(final java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (! isInputValid()) {
            JOptionPane.showMessageDialog(this, 
                    resources.getString("createDialogInvalidInput"));
        } else {
            setStartRequested(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btnStartActionPerformed
    
    /** Closes the dialog */
    private final void closeDialog(final java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    private final boolean isInputValid() {
        return txtName.getText().trim().length() > 0 && 
            txtGiverName.getText().trim().length() > 0;
    }
    
    final boolean isStartRequested() {
        return this.startRequested;
    }    
    
    private final void setStartRequested(final boolean startRequested) {
        this.startRequested = startRequested;
    }
    
    @Override
    public final String getName() {
        return txtName.getText();
    }
    
    @Override
    public final void setName(final String name) {
        txtName.setText(name);
    }
    
    public final String getPassword() {
        final char[] passwordAsChar = txtPassword.getPassword();
        return passwordAsChar.length == 0 ? null : new String(passwordAsChar);
    }
    
    public final void setPassword(final String password) {
        txtPassword.setText(password);
    }
    
    public final String getGiverName() {
        return txtGiverName.getText();
    }
    
    public final void setGiverName(final String giverName) {
        txtGiverName.setText(giverName);
    }
    
    private boolean startRequested;  
    private final ResourceBundle resources = 
            ResourceBundle.getBundle("quickquiz");
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGiverName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

}
